site_name: Cerberus Sandbox
site_description: 'Cerberus Sandbox - Documentation'
site_author: 'Cerberus-Sandbox Team'
docs_dir: docs/
repo_name: 'cerberus-sandbox/cerberus-sandbox.github.io'
repo_url: 'https://github.com/cerberus-sandbox/cerberus-sandbox.github.io'
theme:
  name: 'readthedocs'
